[project]
name = "cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Akshay Priyadarshi", email = "akshayp1904@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "core",
]

[project.scripts]
cli = "cli:main"

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"

[tool.uv.sources]
core = { workspace = true }
